package shirin.tahmasebi.mscfinalproject.io.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import shirin.tahmasebi.mscfinalproject.io.models.Organization;

import shirin.tahmasebi.mscfinalproject.io.models.OrganizationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig organizationDaoConfig;

    private final OrganizationDao organizationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        organizationDaoConfig = daoConfigMap.get(OrganizationDao.class).clone();
        organizationDaoConfig.initIdentityScope(type);

        organizationDao = new OrganizationDao(organizationDaoConfig, this);

        registerDao(Organization.class, organizationDao);
    }
    
    public void clear() {
        organizationDaoConfig.getIdentityScope().clear();
    }

    public OrganizationDao getOrganizationDao() {
        return organizationDao;
    }

}
