package shirin.tahmasebi.mscfinalproject.io.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORGANIZATION.
 */
public class Organization {

    private long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String description;
    /** Not-null value. */
    private String website;

    public Organization() {
    }

    public Organization(long id) {
        this.id = id;
    }

    public Organization(long id, String name, String description, String website) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.website = website;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    /** Not-null value. */
    public String getWebsite() {
        return website;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWebsite(String website) {
        this.website = website;
    }

}
