package shirin.tahmasebi.mscfinalproject.io.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import shirin.tahmasebi.mscfinalproject.io.models.Organization;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ORGANIZATION.
*/
public class OrganizationDao extends AbstractDao<Organization, Long> {

    public static final String TABLENAME = "ORGANIZATION";

    /**
     * Properties of entity Organization.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Website = new Property(3, String.class, "website", false, "WEBSITE");
        public final static Property Image = new Property(4, String.class, "image", false, "IMAGE");
        public final static Property IsFavorite = new Property(5, Boolean.class, "isFavorite", false, "IS_FAVORITE");
        public final static Property SiteUrl = new Property(6, String.class, "siteUrl", false, "SITE_URL");
        public final static Property PhoneNumber = new Property(7, String.class, "phoneNumber", false, "PHONE_NUMBER");
        public final static Property EmailAddress = new Property(8, String.class, "emailAddress", false, "EMAIL_ADDRESS");
    };


    public OrganizationDao(DaoConfig config) {
        super(config);
    }
    
    public OrganizationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ORGANIZATION' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'DESCRIPTION' TEXT NOT NULL ," + // 2: description
                "'WEBSITE' TEXT NOT NULL UNIQUE ," + // 3: website
                "'IMAGE' TEXT NOT NULL ," + // 4: image
                "'IS_FAVORITE' INTEGER," + // 5: isFavorite
                "'SITE_URL' TEXT," + // 6: siteUrl
                "'PHONE_NUMBER' TEXT," + // 7: phoneNumber
                "'EMAIL_ADDRESS' TEXT);"); // 8: emailAddress
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ORGANIZATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Organization entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getDescription());
        stmt.bindString(4, entity.getWebsite());
        stmt.bindString(5, entity.getImage());
 
        Boolean isFavorite = entity.getIsFavorite();
        if (isFavorite != null) {
            stmt.bindLong(6, isFavorite ? 1l: 0l);
        }
 
        String siteUrl = entity.getSiteUrl();
        if (siteUrl != null) {
            stmt.bindString(7, siteUrl);
        }
 
        String phoneNumber = entity.getPhoneNumber();
        if (phoneNumber != null) {
            stmt.bindString(8, phoneNumber);
        }
 
        String emailAddress = entity.getEmailAddress();
        if (emailAddress != null) {
            stmt.bindString(9, emailAddress);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Organization readEntity(Cursor cursor, int offset) {
        Organization entity = new Organization( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // description
            cursor.getString(offset + 3), // website
            cursor.getString(offset + 4), // image
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // isFavorite
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // siteUrl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // phoneNumber
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // emailAddress
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Organization entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setDescription(cursor.getString(offset + 2));
        entity.setWebsite(cursor.getString(offset + 3));
        entity.setImage(cursor.getString(offset + 4));
        entity.setIsFavorite(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setSiteUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPhoneNumber(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEmailAddress(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Organization entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Organization entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
