package shirin.tahmasebi.mscfinalproject.io.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORG_FAV".
 */
public class OrgFav {

    private Long id;
    private Boolean isFavorite;
    private Long no;

    public OrgFav() {
    }

    public OrgFav(Long id) {
        this.id = id;
    }

    public OrgFav(Long id, Boolean isFavorite, Long no) {
        this.id = id;
        this.isFavorite = isFavorite;
        this.no = no;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public Long getNo() {
        return no;
    }

    public void setNo(Long no) {
        this.no = no;
    }

}
