package shirin.tahmasebi.mscfinalproject.io.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REMINDER.
 */
public class Reminder {

    private Long id;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String time;
    /** Not-null value. */
    private String organizationName;
    private String text;

    public Reminder() {
    }

    public Reminder(Long id) {
        this.id = id;
    }

    public Reminder(Long id, String date, String time, String organizationName, String text) {
        this.id = id;
        this.date = date;
        this.time = time;
        this.organizationName = organizationName;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getOrganizationName() {
        return organizationName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
